# Generated by Django 2.2.24 on 2024-05-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
    ]
